SOURCES =  stdlib.ml common.ml syntax.ml ctx.ml pS.ml unify.ml env.ml infer.ml command.ml parser.mly lexer.mll prover.ml catt.ml
RESULT = catt
ANNOTATE = true

all: dnc
	./catt test.catt

include OCamlMakefile
